### ISSUE TITLE
App get crashed

### ISSUE THREAD

**Issue by gdkali** [nikhilmuz/WhatsApp-Bulk-Sender#38]
**Describe the bug**
App gets crashed when i click on the send button

2020-04-24 11:06:37.090 32396-32396/ga.nikhilkumar.whatsappsender E/AndroidRuntime: FATAL EXCEPTION: main
    Process: ga.nikhilkumar.whatsappsender, PID: 32396
    java.lang.RuntimeException: Unable to start service ga.nikhilkumar.whatsappsender.WASenderFgSvc@53bfd77 with Intent { cmp=ga.nikhilkumar.whatsappsender/.WASenderFgSvc (has extras) }: java.lang.ArrayIndexOutOfBoundsException: length=1; index=1
        at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3723)
        at android.app.ActivityThread.access$1600(ActivityThread.java:199)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1687)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6698)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:495)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:859)
     Caused by: java.lang.ArrayIndexOutOfBoundsException: length=1; index=1
        at ga.nikhilkumar.whatsappsender.WASenderFgSvc.send(WASenderFgSvc.java:104)
        at ga.nikhilkumar.whatsappsender.WASenderFgSvc.onStartCommand(WASenderFgSvc.java:88)
        at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3704)
        at android.app.ActivityThread.access$1600(ActivityThread.java:199) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1687) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:193) 
        at android.app.ActivityThread.main(ActivityThread.java:6698) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:495) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:859)

**Comment by gdkali** [comment]
got the problem

**Comment by nikhilmuz** [comment]
Nice to hear you figured it out. If you found any bug due to implementation error do feel free to report. :)
